[Fix] ERF - Default Shift issue
ONE-F-M/One-FM pull request #1370
Opened 2022-09-11 18:12 UTC by pjamsheer

## Feature description
 - ERF Default Shift issue
 - Before PR
 - ![Screenshot 2022-09-09 at 9 44 30 PM](https://user-images.githubusercontent.com/20554466/189542626-cbc972d2-d981-414f-8e93-8cfaad513acf.png)

## Solution description
 - After PR
 - ![Screenshot 2022-09-09 at 9 49 53 PM](https://user-images.githubusercontent.com/20554466/189542650-2b120b78-81d0-422f-92a1-1d8550fe43ee.png)
 - ![Screenshot 2022-09-09 at 9 50 12 PM](https://user-images.githubusercontent.com/20554466/189542651-f4c8ab40-4240-4c49-a4f1-a727ffde04b4.png)

## Is there any existing behavior change of other features due to this code change?
No

## Was this feature tested on all the browsers?
  - [x] Chrome

2022-09-11 20:59 UTC, mymi14s requested changes
Resolve conflict @pjamsheer

2022-09-13 06:09 UTC, mymi14s commented
@pjamsheer did you consider ignore_user_permission on default shift field? that is why the field is always empty for some users

2022-09-13 06:26 UTC, pjamsheer commented
@mymi14s Done

2022-09-13 09:22 UTC, mymi14s approved these changes

2022-09-13 09:22 UTC, merged