addedd datetime module
ONE-F-M/One-FM pull request #1553
Opened 2022-11-28 08:09 UTC by NoBoneZ

## Is this a Feature, Chore or Bug?
- [] Feature
- [] Chore
- [] Bug

## Clearly and concisely describe the feature, chore or bug.

## Analysis and design (optional)
Analyse and attach the design documentation

## Solution description
Describe your code changes in detail for reviewers.

## Is there a business logic within a doctype?
    - [] Yes
    - [] No

## Output screenshots (optional)
Post the output screenshots, if a UI is affected or added due to this feature.

## Areas affected and ensured
List out the areas affected by your code changes.

## Is there any existing behavior change of other features due to this code change?
Mention Yes or No. If Yes, provide the appropriate explanation.

## Did you test with the following dataset?
- [] Existing Data
- [] New Data

## Was child table created?
    - [] is attachment required?
        did you test attachment
## Did you delete custom field?
    - [] Yes
    - [] No
        If yes, did you write a delete patch?

## Is patch required?
- [] Yes
- [] No
    ## Was the patch test?

## Which browser(s) did you use for testing?
  - [] Chrome
  - [] Safari
  - [] Firefox

2022-11-28 08:16 UTC, mymi14s requested changes
@NoBoneZ do not use datetime, instead use frappe.utils.getdate

This uses the company timezone.

Datetime will use utc and company timezone is 3hrs ahead.

2022-11-28 08:21 UTC, NoBoneZ commented
> @NoBoneZ do not use datetime, instead use frappe.utils.getdate
> 
> This uses the company timezone.
> 
> Datetime will use utc and company timezone is 3hrs ahead.

I used it to convert a string to a datetime object, i did not use it to get the current time.

2022-11-28 09:15 UTC, SalShai approved these changes

2022-11-29 05:30 UTC, pjamsheer approved these changes

2022-11-29 05:37 UTC, mymi14s approved these changes

2022-11-29 05:37 UTC, merged