feat: supervisor should receive notificatio, if an employee check in past supervisor notification time
ONE-F-M/One-FM pull request #2044
Opened 2023-03-17 14:02 UTC by NoBoneZ

## Is this a Feature, Chore or Bug?
- [x] Feature
- [] Chore
- [] Bug

## Clearly and concisely describe the feature, chore or bug.
If an emplyee checks in past the supervisor notification time, an email and push notification would be sent to his reports to or supervisor

## Analysis and design (optional)
Analyse and attach the design documentation

## Solution description
Describe your code changes in detail for reviewers.
Added methods that fetches the neccessary information, required to send a notification and email. And to also check if the employee checks in late

## Is there a business logic within a doctype?
    - [] Yes
    - [] No

## Output screenshots (optional)
Post the output screenshots, if a UI is affected or added due to this feature.

## Areas affected and ensured
List out the areas affected by your code changes.
Employee Checkin

## Is there any existing behavior change of other features due to this code change?
Mention Yes or No. If Yes, provide the appropriate explanation.

## Did you test with the following dataset?
- [] Existing Data
- [x] New Data

## Was child table created?
    - [] is attachment required?
        did you test attachment
## Did you delete custom field?
    - [] Yes
    - [x] No
        If yes, did you write a delete patch?

## Is patch required?
- [] Yes
- [x] No
    ## Was the patch test?

## Which browser(s) did you use for testing?
  - [x] Chrome
  - [] Safari
  - [] Firefox

2023-03-18 08:09 UTC, mymi14s requested changes
Make changes

2023-03-18 08:09 UTC, mymi14s commented on one_fm/overrides/employee_checkin.py
> +	last_shift_assignment = frappe.db.sql(f""" select name, shift_type from `tabShift Assignment` where employee = '{checkin.employee}' order by creation desc limit 1 ; """, as_dict=1)
There is roster_type Basic or Overtime. you should factor it in the query, also check if shift assignment exist in the checkin record first, if it exists, the fetch the data else get last active shift .

Avoid using indexing, you can also get data as frappe dict with frappe.db.get_value

2023-03-19 17:16 UTC, NoBoneZ commented on one_fm/overrides/employee_checkin.py
> +	last_shift_assignment = frappe.db.sql(f""" select name, shift_type from `tabShift Assignment` where employee = '{checkin.employee}' order by creation desc limit 1 ; """, as_dict=1)
@mymi14s , changes have been made, kindly review

2023-03-20 20:13 UTC, mymi14s approved these changes

2023-03-20 20:13 UTC, merged