CHORE: Required apps
ONE-F-M/One-FM pull request #2669
Opened 2023-09-03 06:08 UTC by NoBoneZ

## Is this a Feature, Chore or Bug?
- [] Feature
- [x] Chore
- [] Bug

## Clearly and concisely describe the feature, chore or bug.
To add the required apps to the hooks.py and the readme

## Analysis and design (optional)
Analyse and attach the design documentation

## Solution description
Describe your code changes in detail for reviewers.

## Is there a business logic within a doctype?
    - [] Yes
    - [x] No

## Output screenshots (optional)
Post the output screenshots, if a UI is affected or added due to this feature.

## Areas affected and ensured
List out the areas affected by your code changes.

## Is there any existing behavior change of other features due to this code change?
Mention Yes or No. If Yes, provide the appropriate explanation.

## Did you test with the following dataset?
- [] Existing Data
- [x] New Data

## Was child table created?
    - [] is attachment required?
        did you test attachment
## Did you delete custom field?
    - [] Yes
    - [x] No
        If yes, did you write a delete patch?

## Is patch required?
- [] Yes
- [x] No
    ## Was the patch test?

## Which browser(s) did you use for testing?
  - [x] Chrome
  - [] Safari
  - [] Firefox

2023-09-03 17:44 UTC, Talleyrand333 approved these changes

2023-09-03 17:44 UTC, mymi14s requested changes
ONE FM does not use LMS, ONE LMS, ONE FM WEBSITE. Click on Help on frappe desk, then about to see the instaled apps.

2023-09-03 19:43 UTC, mymi14s requested changes
This is wrong, the app name is not capitalized neither is there space. Please fix with the correct app name, check the git repos. e.g One Wiki is one_wiki

2023-09-05 19:43 UTC, mymi14s approved these changes

2023-09-05 19:43 UTC, merged