features:Mobile API for accept/reject penalty && various features and…
ONE-F-M/One-FM pull request #339
Opened 2021-05-31 10:40 UTC by osamaasim

… hotfixes in RFM/RFP

- Added mobile API for accepting and rejecting penalties (Kartik)
- UX improvements in RFM for Stock Entries and RFPs created against it.
- Notification to purchase user for RFM reinstated
- Quantity to transfer separated in RFM item
- Quantity to purchase or transfer made editable

2021-05-31 11:27 UTC, ks093 requested changes
@osamaasim Line 142.
Instead of doing return message, frappe.throw should be used for mobile app. It will raise a proper error on the app side.

2021-06-01 06:30 UTC, osamaasim commented
> @osamaasim Line 142.
> Instead of doing return message, frappe.throw should be used for mobile app. It will raise a proper error on the app side.

@ks093 I have made the required changes. Please review.

2021-06-01 07:02 UTC, ks093 commented
> > @osamaasim Line 142.
> > Instead of doing return message, frappe.throw should be used for mobile app. It will raise a proper error on the app side.
> 
> @ks093 I have made the required changes. Please review.

@osamaasim @pjamsheer Reviewed the penalty part. All good.

2021-06-01 07:17 UTC, pjamsheer approved these changes

2021-06-01 07:18 UTC, merged