CHORE: MERGE VERSION-15 AND STAGING INTO ATTENDANCE BRANCH
ONE-F-M/One-FM pull request #3580
Opened 2024-08-21 14:14 UTC by NoBoneZ

## Is this a Feature, Chore or Bug?
- [] Feature
- [X] Chore
- [] Bug

## Clearly and concisely describe the feature, chore or bug.
Merge Version-15 and staging branch into attendance

## Analysis and design (optional)
Analyse and attach the design documentation

## Solution description
Describe your code changes in detail for reviewers.

## Is there a business logic within a doctype?
    - [] Yes
    - [] No

## Output screenshots (optional)
Post the output screenshots, if a UI is affected or added due to this feature.

## Areas affected and ensured
List out the areas affected by your code changes.

## Is there any existing behavior change of other features due to this code change?
Mention Yes or No. If Yes, provide the appropriate explanation.

## Did you test with the following dataset?
- [] Existing Data
- [] New Data

## Was child table created?
    - [] is attachment required?
        did you test attachment
## Did you delete custom field?
    - [] Yes
    - [] No
        If yes, did you write a delete patch?

## Is patch required?
- [] Yes
- [] No
    ## Was the patch test?

## Which browser(s) did you use for testing?
  - [] Chrome
  - [] Safari
  - [] Firefox

2024-09-03 13:56 UTC, pjamsheer requested changes

2024-09-03 13:56 UTC, pjamsheer commented on one_fm/public/js/doctype_js/attendance_request.js
> +<<<<<<< HEAD
Please check this line number 4, 7 ,.........

2024-09-03 13:56 UTC, pjamsheer commented on one_fm/public/js/doctype_js/employee_checkin.js
> +<<<<<<< HEAD
Please review this file

2024-09-03 13:56 UTC, pjamsheer commented on one_fm/one_fm/custom/shift_request.json
> +<<<<<<< HEAD
Please check this file

2024-09-03 13:56 UTC, pjamsheer commented on one_fm/public/js/doctype_js/timesheet.js
> +<<<<<<< HEAD
Please check this file

2024-09-03 13:56 UTC, pjamsheer commented on one_fm/public/swagger/one_fm_v1.json
Please check this file

2024-09-04 06:43 UTC, NoBoneZ commented on one_fm/public/js/doctype_js/timesheet.js
> +<<<<<<< HEAD
@pjamsheer , changes have been made

2024-09-04 06:43 UTC, NoBoneZ commented on one_fm/one_fm/custom/shift_request.json
> +<<<<<<< HEAD
@pjamsheer , changes have been made

2024-09-04 06:43 UTC, NoBoneZ commented on one_fm/public/js/doctype_js/attendance_request.js
> +<<<<<<< HEAD
@pjamsheer , changes have been made

2024-09-04 06:43 UTC, NoBoneZ commented on one_fm/public/js/doctype_js/employee_checkin.js
> +<<<<<<< HEAD
@pjamsheer , changes have been made

2024-09-09 09:10 UTC, pjamsheer requested changes

2024-09-09 09:10 UTC, pjamsheer commented on one_fm/public/js/doctype_js/attendance_request.js
> +    set_update_request_btn(frm);
This method is not defined(we have removed it)

2024-09-11 11:02 UTC, NoBoneZ commented on one_fm/public/js/doctype_js/attendance_request.js
> +    set_update_request_btn(frm);
@pjamsheer , i have resolved this

2024-09-11 12:29 UTC, pjamsheer requested changes

2024-09-11 12:29 UTC, pjamsheer commented on one_fm/overrides/shift_request.py
> +<<<<<<< HEAD
Please check this file

2024-09-11 17:54 UTC, NoBoneZ commented on one_fm/overrides/shift_request.py
> +<<<<<<< HEAD
@pjamsheer resolved

2024-09-16 05:46 UTC, pjamsheer approved these changes

2024-09-16 05:48 UTC, merged