CHORE: ADDED CHANGLOG FOR SPRINT 129
ONE-F-M/One-FM pull request #3608
Opened 2024-09-04 06:42 UTC by NoBoneZ

## Is this a Feature, Chore or Bug?
- [] Feature
- [X] Chore
- [] Bug

## Clearly and concisely describe the feature, chore or bug.
To add the changelog for the lsat sprint(sprint 129)

## Analysis and design (optional)
Analyse and attach the design documentation

## Solution description
Describe your code changes in detail for reviewers.

## Is there a business logic within a doctype?
    - [] Yes
    - [] No

## Output screenshots (optional)
Post the output screenshots, if a UI is affected or added due to this feature.

## Areas affected and ensured
List out the areas affected by your code changes.
Change Log

## Is there any existing behavior change of other features due to this code change?
Mention Yes or No. If Yes, provide the appropriate explanation.

## Did you test with the following dataset?
- [] Existing Data
- [] New Data

## Was child table created?
    - [] is attachment required?
        did you test attachment
## Did you delete custom field?
    - [] Yes
    - [x] No
        If yes, did you write a delete patch?

## Is patch required?
- [] Yes
- [x] No
    ## Was the patch test?

## Which browser(s) did you use for testing?
  - [] Chrome
  - [] Safari
  - [] Firefox

2024-09-04 17:18 UTC, pjamsheer requested changes
Add change in one_fm/__init__.py  Line 54 from `__version__ = '15.1.0'` to `__version__ = '15.1.1'`

2024-09-04 17:18 UTC, pjamsheer commented on one_fm/change_log/v15/v15_1_1.md
> +# Version 15.1.0 Release Notes
This is version 15.1.1

2024-09-05 06:19 UTC, NoBoneZ commented
> __version__

@pjamsheer , done

2024-09-05 07:02 UTC, pjamsheer approved these changes

2024-09-05 07:04 UTC, merged