Hajj check
ONE-F-M/One-FM pull request #3712
Opened 2024-10-14 08:25 UTC by samdanikouser

## Is this a Feature, Chore or Bug?
- Story

## Clearly and concisely describe the feature, chore or bug.
          [] I want to allocate Hajj leave only to Muslim staff members who have not performed Hajj before so that unqualified employees are not allocated Hajj leave
        
        Acceptance Criteria
        Given that a leave allocation is being created or edited and the leave type is "Hajj Leave"
        when the user clicks save
        then the system validates that the Employee is a muslim who has not performed Hajj. If these 2 conditions are not met, a message is shown and the process is aborted
        
        Notes:
        -Hajj Leave allocation is only allowed for a muslim staff Who has not performed Hajj before.
        -[Religion] and [Went to Hajj] are fields in the Employee doctype
        
        Consider moving [Went to Hajj] to "Personal" tab, after Religion and it should only be editable if [Religion] is set as "Muslim" (Depends on: eval: Religion == "Muslim").

## Analysis and design (optional)
[Analyse and attach the design documentation
](https://lucid.app/lucidchart/37a0e91b-1f10-40d0-bb6c-e7126f57eb57/edit?page=2tkbzzr9QS2v#)

## Solution description
---  Code changes in employee.js file of docstype.js ,added a check to religion if muslim to enable the went to hajj checkbox else to disable it .
--- Code changes in leave_allocation.py file for checking if religion is muslim to allocate the leave for that specific employee

## Is there a business logic within a doctype?
    - [] No

## Output screenshots (optional)
<img width="427" alt="Screenshot 2024-10-14 at 11 21 27 AM" src="https://github.com/user-attachments/assets/0c259cde-5ce2-4ed5-a0f8-3a2bcb65dbdc">

<img width="531" alt="Screenshot 2024-10-14 at 11 21 39 AM" src="https://github.com/user-attachments/assets/c221a0f5-417b-4de3-bf61-9d16de1e0384">List out the areas affected by your code changes.

## Leave Allocation screenshort
<img width="683" alt="Screenshot 2024-10-14 at 11 22 34 AM" src="https://github.com/user-attachments/assets/bafec3f6-a816-45f9-807b-f639c15ebd72">

## Is there any existing behavior change of other features due to this code change?
 Yes - The went to hajj field is been shifted to the personal details from the attedance in the employee profile page

## Did you delete custom field?
    - [] No

## Is patch required?
- [] No

## Which browser(s) did you use for testing?
  - [] Chrome
  - [] Safari
  - [] Firefox

2024-10-14 08:35 UTC, NoBoneZ commented on one_fm/overrides/leave_allocation.py
> +        religion, went_to_hajj = frappe.db.get_value("Employee", self.employee, ["one_fm_religion", "went_to_hajj"])
Kindly avoid explosion, it caused issues in previous development iterations, you could use the , as_dict kwarg, then use the dictionary method, to get th eneeded fields

2024-10-14 08:35 UTC, NoBoneZ commented on one_fm/overrides/leave_allocation.py
> +    def validate_employee_gender(self):
kindly merge staging into this branch

2024-10-14 08:36 UTC, NoBoneZ commented on one_fm/fixtures/doctype_layout.json
> +   {
KIndly run migrations on your local bench, and confirm that this works as excpected

2024-10-14 08:40 UTC, NoBoneZ requested changes
KIndly check the comments

2024-10-15 07:43 UTC, Talleyrand333 commented
@samdanikouser Please check the file changes. there should not be so many changes for this.

2024-10-15 08:37 UTC, closed without merging