FEAT : As OneFM I want to revert transferred responsibilities after Employee's leave duration
ONE-F-M/One-FM pull request #3832
Opened 2024-12-02 10:30 UTC by samdanikouser

## Is this a Feature, Chore or Bug?
- [] Feature

## Clearly and concisely describe the feature, chore or bug.
Reassigning the employees responsibility after the employee came from vacation 

## Analysis and design (optional)
[Analyse and attach the design documentation
](https://lucid.app/lucidchart/37a0e91b-1f10-40d0-bb6c-e7126f57eb57/edit?invitationId=inv_b5ee333d-aeee-4565-8774-87103ecbf202&page=lnHdce9qPoSl#)

## Solution description
changes in the reliver_assigment.py file

## Is there a business logic within a doctype?
    - [] No

## Output screenshots (optional)
<img width="1058" alt="Screenshot 2024-12-02 at 1 28 00 PM" src="https://github.com/user-attachments/assets/cba4d740-0620-4618-9855-e073c0e505c2">

## Areas affected and ensured
Reliever assignment status - Employee reporter - user permission - projects - todos - operation sites - routine task - simgle doctype - approvals

## Is there any existing behavior change of other features due to this code change?
No.

## Did you test with the following dataset?
- [] Existing Data

## Was child table created?
    - [NO] is attachment required?

## Did you delete custom field?
    - [] No

## Is patch required?
- [] No

## Which browser(s) did you use for testing?
  - [] Chrome
  - [] Safari
  - [] Firefox

2024-12-03 04:57 UTC, ks093 requested changes

2024-12-03 04:57 UTC, ks093 commented on one_fm/one_fm/doctype/reliever_assignment/reliever_assignment.py
> +		reliver_roles = set(doclist.get("reliever",{}).get("roles",[]))
@samdanikouser Typo. Please fix reliver_roles to reliever_roles.

2024-12-03 04:57 UTC, ks093 commented on one_fm/one_fm/doctype/reliever_assignment/reliever_assignment.py
> +		datas = (frappe.qb.from_("Reliever Assignment Document")\
@samdanikouser Don't need to get the "datas" again. You already have everything available in self.parent_data.

2024-12-03 13:05 UTC, samdanikouser commented on one_fm/one_fm/doctype/reliever_assignment/reliever_assignment.py
> +		datas = (frappe.qb.from_("Reliever Assignment Document")\
@ks093 Changed as mentioned in the comments and tested the same in local

2024-12-03 13:05 UTC, samdanikouser commented on one_fm/one_fm/doctype/reliever_assignment/reliever_assignment.py
> +		reliver_roles = set(doclist.get("reliever",{}).get("roles",[]))
@ks093 Changed as mentioned in the comments and tested the same in local

2024-12-05 11:18 UTC, ks093 approved these changes

2024-12-05 11:18 UTC, merged