Returning the Retries Left if face recognition Fails.
ONE-F-M/One-FM pull request #685
Opened 2021-11-17 09:42 UTC by SalShai

## Feature description
This is an API to accept penalties. To Accept a Penalty, one needs to pass the face recognition test. Image file in base64 format is passed through the face recognition test. And, the employee is given 3 tries. If face recognition is true, the penalty gets excepted. If Face recognition fails even after 3 tries, the image is sent to the legal manager for investigation. 

## Solution description
Send response using Response API. 
If Success = True, Status would be 200.
If Face recognition fails, return back the Retries left in data_obj.

## Output screenshots (optional)
On success:
<img width="300" alt="Screen Shot 2021-11-16 at 7 44 32 PM" src="https://user-images.githubusercontent.com/29017559/142171468-f1a9eb1b-acf2-4d1a-a611-67f906ee6d95.png">

On Fail:
<img width="300" alt="Screen Shot 2021-11-16 at 7 50 56 PM" src="https://user-images.githubusercontent.com/29017559/142171478-692d5e16-33ec-4198-a804-f3c385a35035.png">

## Areas affected and ensured
Accept Penalty API Response structure is Changed.

## Is there any existing behavior change of other features due to this code change?
yes, Response for Accept_Penalty.

## Was this feature tested on all the browsers?
  - [x] Chrome
  - [x] Safari

2021-11-17 12:05 UTC, Amna-onefm requested changes
@SalShai Also, remove all print in `one_fm/legal/doctype/penalty/penalty.py` file

2021-11-17 12:05 UTC, Amna-Alshawa commented on one_fm/api/mobile/legal.py
> +			return response("Face Recognition Failed. You have "+str(retries_left)+" retries left.", False ,{"retries_left":retries_left},401)
Try to set the response args in this way:
**response( `message` , `data` ,  `success` , `status code` )** 
to unite all api responses.

2021-11-17 12:05 UTC, Amna-Alshawa commented on one_fm/utils.py
> +def response(message, success, data, status_code):
Make sure you update the parameters in the header definition of the `response`  method.

2021-11-17 12:05 UTC, Amna-Alshawa commented on one_fm/api/mobile/legal.py
> -			penalty.workflow_state = "Penalty Accepted"
@SalShai ,you are accepting penalties even before the three tries!!

2021-11-17 12:05 UTC, Amna-onefm commented on one_fm/api/mobile/legal.py
> +	If face recognition is true, the penalty gets excepted.
Do you mean the penalty gets `accepted`, so `excepted` is a typo issue?

2021-11-17 12:09 UTC, SalShai commented on one_fm/api/mobile/legal.py
> +			return response("Face Recognition Failed. You have "+str(retries_left)+" retries left.", False ,{"retries_left":retries_left},401)
how does that make any difference ?

2021-11-17 12:16 UTC, Amna-onefm commented on one_fm/api/mobile/legal.py
> +			return response("Face Recognition Failed. You have "+str(retries_left)+" retries left.", False ,{"retries_left":retries_left},401)
no difference but organizing and unifying API  responses.

2021-11-18 06:50 UTC, Amna-Alshawa approved these changes
@SalShai Greate

2021-11-18 07:51 UTC, merged