Feat: Report of Approved Purchase Document
ONE-F-M/One-FM pull request #786
Opened 2022-01-05 14:04 UTC by SalShai

## Feature description
Report of the documents approved in the Purchase Process.

## Solution description
Create a report using Version Doctype to fetch all the doctypes and the doc link, if it was approved by the user.

## Output screenshots (optional)
<img width="991" alt="Screen Shot 2022-01-05 at 4 21 30 PM" src="https://user-images.githubusercontent.com/29017559/148230156-1d2bd9de-7d6d-4f07-8751-b2c92883d551.png">

## Areas affected and ensured
- New Report Created.
- Enable "Track The Changes" in the 'Request for Purchase' Doctype.
-
## Is there any existing behavior change of other features due to this code change?
-Changes tracked in 'Request for Purchase' Doctype.

## Was this feature tested on all the browsers?
  - [x] Chrome
  - [x] Safari

2022-01-05 14:33 UTC, mymi14s commented
Please add the workflow_state (original_value, new_value) to the report columns.
This will report the old and new value of the approval, Thanks.

![image](https://user-images.githubusercontent.com/10146518/148234705-437b6d36-7fe3-4336-950f-3b1384fced95.png)

2022-01-05 14:37 UTC, mymi14s requested changes
Also return the report with values sorted by approval date DESC

2022-01-06 05:20 UTC, SalShai commented
@mymi14s Could you elaborate more on why do we need old values? While we could just be displaying the current status.

2022-01-06 05:20 UTC, SalShai commented
Sure, let me sort approval date by DESC.

2022-01-06 05:52 UTC, mymi14s commented
> @mymi14s Could you elaborate more on why do we need old values? While we could just be displaying the current status.

So that the report can show what action was taken from x to y.

2022-01-06 05:54 UTC, SalShai commented
The action is always from Draft to Approved😅

2022-01-06 05:55 UTC, SalShai commented
> > @mymi14s Could you elaborate more on why do we need old values? While we could just be displaying the current status.
> 
> So that the report can show what action was taken from x to y.

The action is always from Draft to Approved😅

2022-01-06 06:02 UTC, SalShai commented
> > > @mymi14s Could you elaborate more on why do we need old values? While we could just be displaying the current status.
> > 
> > 
> > So that the report can show what action was taken from x to y.
> 
> @mymi14s , The action is always from Draft to Approved😅

@taqi-onefm , Could you please Clarify the doubt??

2022-01-06 06:08 UTC, mymi14s approved these changes
Good to go

2022-01-06 06:10 UTC, merged